# 붓꽃 품종 예측하기 (scikit-learn)

In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
import numpy as np

#### 붓꽃 데이터 세트 로딩

In [3]:
iris = load_iris()

In [4]:
iris_data = iris.data

In [5]:
iris_label = iris.target

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

#### 데이터 세트를 자세히 보기 위해 DataFrame으로 변환

In [7]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [8]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   label              150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [9]:
iris_df['label'].unique()

array([0, 1, 2])

#### train_test_split() 이용하여 학습용, 테스트용 데이터를 분할

In [10]:

X_train, X_test, y_train, y_test = train_test_split( iris_data, iris_label, test_size=0.2, random_state=11)

#### 머신러닝 분류 알고리즘의 하나인 의사 결정 트리(decision tree classifier) 객체 생성

In [11]:
dt_clf = DecisionTreeClassifier(random_state=11)

#### 학습 수행

In [12]:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

#### 학습 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행

In [13]:
pred = dt_clf.predict(X_test)

In [14]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [15]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [16]:
from sklearn.metrics import accuracy_score

#### 예측 정확도

In [17]:
accuracy_score(y_test, pred)

0.9333333333333333

In [18]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])